apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: algoarena
  namespace: algoarena
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: algoarena.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: algoarena-backend
                port:
                  number: 3000
          - path: /uploads
            pathType: Prefix
            backend:
              service:
                name: algoarena-backend
                port:
                  number: 3000
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: algoarena-backend
                port:
                  number: 3000
          - path: /chat/ws
            pathType: Prefix
            backend:
              service:
                name: algoarena-backend
                port:
                  number: 3000
          - path: /battles/ws
            pathType: Prefix
            backend:
              service:
                name: algoarena-backend
                port:
                  number: 3000
          - path: /auth/google
            pathType: Prefix
            backend:
              service:
                name: algoarena-backend
                port:
                  number: 3000
          - path: /auth/github
            pathType: Prefix
            backend:
              service:
                name: algoarena-backend
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: algoarena-frontend
                port:
                  number: 80
